[TRAD-14] [Fazer o Processamento das mensagens recebidas pelo pubsub]
ditointernet/tradulab-service pull request #10
Opened 2021-10-27 19:26 UTC by gabrielmirandaBR

O objetivo geral da tarefa foi receber a mensagem do Pub/Sub e realizar o seu processamento.

Quando a pessoa usuária fizer um upload o status do arquivo no banco de dados será alterado para "SUCCESS".

2021-10-29 18:52 UTC, nborgesfilho requested changes

2021-10-29 18:52 UTC, nborgesfilho commented on cmd/pubsub/pubsub.go
> +		fmt.Println("new message received")
Favor criar uma outra struct em um outro repositório chamado Handler para que ele consiga realizar o manuseio da mensagem recebida.
Um comparativo com o binário de microsserviço, este arquivo atual é o main.go do binário da API e o Handler seria a controladora.

2021-10-29 19:15 UTC, SPascareli commented
Não entendi pq temos 2 PRs que definem o subscriber, essa aqui contém a lógica de processamento, mas a TRAD-13 só tem a main e o storage...Qual das duas é a final?

2021-10-29 19:18 UTC, SPascareli requested changes

2021-10-29 19:18 UTC, SPascareli commented on cmd/pubsub/pubsub.go
> +			panic(err)
A gente vai parar o subscriber sempre que uma mensagem for mal formatada?

2021-10-29 19:18 UTC, SPascareli commented on cmd/pubsub/pubsub.go
> +		m.Ack()
`EditFile` nunca pode falhar?

2021-10-29 19:18 UTC, SPascareli commented on internal/core/services/contracts.go
> +}
Por que isso aqui ta nessa PR?

2021-10-29 19:18 UTC, SPascareli commented on internal/storage/storage.go
> +package storage
Pq esse pacote ta sendo adicionado nessa PR, se aparentemente ele não é usado?

2021-10-29 19:49 UTC, Melissa-gomes commented
> Não entendi pq temos 2 PRs que definem o subscriber, essa aqui contém a lógica de processamento, mas a TRAD-13 só tem a main e o storage...Qual das duas é a final?

A final é a 14, nós puxamos a 14 com base na 13 pois para dar prosseguimento na tarefa, nós precisávamos do código da 13, e como ainda não tínhamos dado merge na 13 por falta de CR os códigos ficaram duplicados.

2021-10-29 19:51 UTC, SPascareli commented
> > Não entendi pq temos 2 PRs que definem o subscriber, essa aqui contém a lógica de processamento, mas a TRAD-13 só tem a main e o storage...Qual das duas é a final?
> 
> A final é a 14, nós puxamos a 14 com base na 13 pois para dar prosseguimento na tarefa, nós precisávamos do código da 13, e como ainda não tínhamos dado merge na 13 por falta de CR os códigos ficaram duplicados.

Recomendo então mudar essa PR pra apontar pra 13 ao invés da master, assim a gente avalia só essa PR em isolamento.
Ai essa 14 vai mergear na 13, e a 13 na master.

2021-10-29 19:53 UTC, Melissa-gomes commented
> > > Não entendi pq temos 2 PRs que definem o subscriber, essa aqui contém a lógica de processamento, mas a TRAD-13 só tem a main e o storage...Qual das duas é a final?
> > 
> > 
> > A final é a 14, nós puxamos a 14 com base na 13 pois para dar prosseguimento na tarefa, nós precisávamos do código da 13, e como ainda não tínhamos dado merge na 13 por falta de CR os códigos ficaram duplicados.
> 
> Recomendo então mudar essa PR pra apontar pra 13 ao invés da master, assim a gente avalia só essa PR em isolamento. Ai essa 14 vai mergear na 13, e a 13 na master.

Faz sentido, obrigada, já mudamos

2021-11-01 15:00 UTC, pdropaiva requested changes

2021-11-01 15:05 UTC, pdropaiva requested changes

2021-11-01 15:05 UTC, pdropaiva commented on cmd/pubsub/pubsub.go
> +		fmt.Println("Couldn't create a new client", err.Error())
Aqui pra mim faz sentido ser panic, se der erro para gerar o client do pubsub, nada após isso aqui irá funcionar.

2021-11-01 15:05 UTC, pdropaiva commented on cmd/pubsub/pubsub.go
>  	sub := client.Subscription("files-topic-sub")
O que acham de adicionar a subscription em variável de ambiente?

2021-11-04 14:08 UTC, SPascareli requested changes

2021-11-04 14:26 UTC, gabrielmirandaBR commented on internal/subscriber/message.go
> +	}
o `Ack` seria a confirmação da mensagem após o seu processamento ser concluído e diz para o pub/sub que não preciso vê-la mais (deu tudo certo).

O `Nack` seria a perda da mensagem e diz para o pub/sub reenviá-la (ocorreu algum erro).

Seria isso, @SPascareli ?

2021-11-04 14:51 UTC, SPascareli commented on internal/subscriber/message.go
> +	}
Isso mesmo!

2021-11-04 14:58 UTC, SPascareli commented on internal/subscriber/message.go
> +		m.Nack()
Só um comentário aqui, o `Nack` indica pro pubsub que ele deve tentar reenviar a mensagem, geralmente isso é bom quando acontece um erro temporário durante o processamento, tipo um erro de rede ou algo assim, que se vc tentar novamente pode estar resolvido.

Porém nesse caso aqui se o json da mensagem ta errado ele **nunca** vai funcionar, não importa quantas vezes a mensagem for reenviada, por que o `Data` de uma mensagem nunca muda, então não tem muito sentido tentar novamente.

Eu prefiro fazer `Ack` nesses casos e logar o erro, mas existem discordâncias nesse aspécto, algumas pessoas preferem fazer o `Nack` e deixar a mensagem reenviar até cair na DLQ. Nesse caso vc pode configurar para ser alertado quando a mensagem cai na DLQ, mas não tem muito o que possa fazer já que o json ta errado de qualquer forma, então por isso prefiro `Ack` e logar, mas vai de cada um.

2021-11-04 15:07 UTC, brendalima commented on internal/subscriber/message.go
> +	err = s.sFile.EditFile(ctx, file)
Ele edita o Status da mensagem para `SUCCESS`. Quando ele recebe uma mensagem do pubsub, ele sabe que o arquivo foi subido com sucesso na storage e atualiza no nosso banco de dados pra sabermos que aquele arquivo já está disponível na plataforma.

2021-11-04 15:08 UTC, SPascareli commented on internal/subscriber/message.go
> +	err = s.sFile.EditFile(ctx, file)
> Ele edita o Status da mensagem para SUCCESS

Consegue pensar em um nome que deixa mais claro que esse método faz isso?

2021-11-04 15:11 UTC, brendalima commented on internal/subscriber/message.go
> +	err = s.sFile.EditFile(ctx, file)
No caso ele só precisa do `ID` do file pra saber qual é o arquivo no nosso banco que foi subido na plataforma. O campo de status é o único campo editável do nosso arquivo e ele só tem as opções de created quando é criado no banco e de success quando é subido na plataforma, por enquanto.

2021-11-04 15:21 UTC, SPascareli commented on internal/subscriber/message.go
> +	err = s.sFile.EditFile(ctx, file)
Pensa assim, o motivo de termos essa separação entre camadas do código é pro consumidor (no caso o subscriber) não precisar conhecer todos os detalhes de implementação do provedor,  porém do jeito que ta hoje o consumidor tem que saber:

1. Ele tem que passar o `ID` do file preenchido;
2. Que o único campo editável do file é o `status`;
3. Que quando ele chama o `EditFile` ele vai setar o `status` do file pra `SUCCESS`.

Sem esse conhecimento interno o consumidor ficaria completamente sem entender o que do file de fato ta sendo editado nesse `EditFile`.

Dado isso, eu acredito que vcs conseguem pensar num nome mais explicativo pra esse método, um nome que seja claro qual ação está sendo realizada quando vc chama ele.

2021-11-04 18:48 UTC, brendalima commented on internal/subscriber/message.go
> +		m.Nack()
Entendi, Sérgio! Realmente, faz sentido!

2021-11-04 21:24 UTC, SPascareli requested changes
Algumas questões de nomeclatura.

2021-11-04 21:24 UTC, SPascareli commented on internal/core/services/contracts.go
> +	UpdateFileStatus(ctx context.Context, file *domain.File) error
Pensando que esse método é a nível de service, e que ele é chamado quando o upload do arquivo acontece com sucesso, eu penso que nomes mais adequados seriam tipo:

- `SetUploadSuccessful`
- `SetSuccesful`
- `SuccessfulUpload`

Algo desse tipo. Se houver por exemplo uma versão de "falha", ela poderia ser:

- `SetUploadFailed`
- `SetFailed`
- `FailedUpload`

Outra forma de fazer seria manter o nome atual, mas receber tipo um `UploadStatus`, assim esse método serviria pra qualquer status existente:

```
UpdateFileStatus(ctx, file, status.Success
---
UpdateFileStatus(ctx, file, status.Fail)
```

2021-11-04 21:24 UTC, SPascareli commented on internal/repository/contracts.go
> +	UpdateFileStatus(ctx context.Context, file *domain.File) error
Pensando que esse método é a nivel de repository, acho que `UpdateFileStatus` só faz sentido se ele receber o status que o service quer setar, ao invés de setar o status de `SUCCESS` fixo, não acha?

2021-11-08 13:21 UTC, SPascareli approved these changes

2021-11-08 15:31 UTC, pdropaiva approved these changes

2021-11-09 20:39 UTC, merged