[TRAD-15] Fazer o download do arquivo no subscriber
ditointernet/tradulab-service pull request #11
Opened 2021-11-11 14:18 UTC by brendalima

2021-11-12 19:52 UTC, nborgesfilho requested changes

2021-11-12 19:52 UTC, nborgesfilho commented on internal/subscriber/message.go
> +func DownloadDoc(ctx context.Context, docName string, strg storage.Storage) error {
O que acha de criar um handler para realizar esse download e colocar como um método desse handler?

2021-11-18 13:50 UTC, Melissa-gomes commented on internal/subscriber/message.go
> +func DownloadDoc(ctx context.Context, docName string, strg storage.Storage) error {
@nborgesfilho  da uma olhadinha na TRAD-16 pra ver se já atende o que você espera.

2021-11-18 15:00 UTC, SPascareli commented on internal/subscriber/message.go
> +func (s Subscriber) HandleMessage(ctx context.Context, m *pubsub.Message, strg storage.Storage) error {
O service de file vcs tão passando por injeção, mas o storage vcs tão passando por parâmetro, tem algum motivo pra isso ser diferente?

2021-11-18 15:00 UTC, SPascareli commented on internal/subscriber/message.go
> +
espaço

2021-11-18 15:01 UTC, SPascareli commented on internal/subscriber/message.go
> +	rc, err := strg.BucketHandle.Object(docName).NewReader(ctx)
Baixando em memória e não em disco, bom demais :clap: :clap: :clap:

2021-11-18 15:04 UTC, Melissa-gomes commented on internal/subscriber/message.go
> +
retirei o espaço desnecessário.

2021-11-18 15:07 UTC, gabrielmirandaBR commented on internal/subscriber/message.go
> +func (s Subscriber) HandleMessage(ctx context.Context, m *pubsub.Message, strg storage.Storage) error {
Não temos uma justificava específica. Acha válido passarmos esse parâmetro via injenção?

2021-11-18 15:28 UTC, SPascareli commented on internal/subscriber/message.go
> +func (s Subscriber) HandleMessage(ctx context.Context, m *pubsub.Message, strg storage.Storage) error {
Honestamente eu acho válido dos 2 jeitos, mas talvez não ao mesmo tempo.

Algo que muda a cada mensagem tem que ser passado via parâmetro, tipo o `*pubsub.Message` e o `ctx`, e algo que é instanciado no começo do programa e não muda durante a execução pode ser passado via injeção. Nesse caso vc estaria passando algo que nunca muda (o `Storage` client) em toda chamada.

2021-11-18 18:14 UTC, gabrielmirandaBR commented on internal/subscriber/message.go
> +func (s Subscriber) HandleMessage(ctx context.Context, m *pubsub.Message, strg storage.Storage) error {
Bem interessante esse conceito de passar por injeção somente aqueles atributos imutáveis, não sabia. Nesse caso, resolvemos passar via injeção mesmo, uma vez que, a estrutura do `Storage` não será alterada.

2021-11-22 13:58 UTC, SPascareli approved these changes
Sugiro não esperar muito pra mergear essa aqui, eu acho que ela ta ficando desatualizada pq as mudanças principais estão na 16.

2021-11-22 17:48 UTC, uriell approved these changes

2021-11-22 17:53 UTC, merged