[TRAD-16] Criar o handler de arquivos json para o contrato de Phrase no subscriber e Persistir as phrases no banco de dados
ditointernet/tradulab-service pull request #12
Opened 2021-11-18 13:49 UTC by brendalima

Cria handler de json para Phrases ao receber um novo arquivo no subscriber e persiste no banco de dados de acordo com as condições:
`+` existe no arquivo, não existe no banco - cria uma phrase no banco
`~` existe no arquivo, existe no banco, conteúdo tá diferente - update na mesma phrase no banco
`-` não existe no arquivo, existe no banco - remove a phrase do banco

2021-11-19 21:16 UTC, nborgesfilho requested changes

2021-11-19 21:16 UTC, nborgesfilho commented on internal/core/services/phrase.go
> +		//storage: storage,
Favor remover código comentado.

2021-11-19 21:16 UTC, nborgesfilho commented on internal/core/services/phrase.go
> +	//storage storage.FileStorage
Pq este service precisa de um storage  como dependência?

2021-11-19 21:16 UTC, nborgesfilho commented on internal/core/services/phrase.go
> +	result, err := p.repo.GetPhrase(ctx, *entry)
O nome do método não está condizente com o que ele está fazendo.
Ele está verificando e atualizando a phrase.

2021-11-19 21:16 UTC, nborgesfilho commented on internal/repository/phrase.go
> +		"SELECT key FROM phrases WHERE key = $1 and file_id = $2",
Talvez utilizar o Gorm?

2021-11-19 21:16 UTC, nborgesfilho commented on internal/repository/phrase.go
> +		"INSERT into phrases (id, file_id, key, content) values ($1, $2, $3, $4)",
Talvez utilizar o Gorm?

2021-11-19 21:16 UTC, nborgesfilho commented on internal/repository/phrase.go
> +		"UPDATE phrases SET content = $2 WHERE key = $1 AND file_id = $3",
Talvez utilizar o Gorm?

2021-11-19 21:16 UTC, nborgesfilho commented on internal/repository/phrase.go
> +		"SELECT key FROM phrases WHERE file_id = $1",
Talvez utilizar o Gorm?

2021-11-19 21:16 UTC, nborgesfilho commented on internal/repository/phrase.go
> +	query := fmt.Sprintf("DELETE FROM phrases WHERE file_id = $1 AND key NOT IN (%s)", list)
Talvez utilizar o Gorm?

2021-11-22 12:56 UTC, Melissa-gomes commented on internal/repository/phrase.go
> +		"SELECT key FROM phrases WHERE key = $1 and file_id = $2",
Não vamos usar Gorm, isso foi decidido la atrás.

2021-11-22 12:56 UTC, Melissa-gomes commented on internal/repository/phrase.go
> +		"UPDATE phrases SET content = $2 WHERE key = $1 AND file_id = $3",
Não vamos usar Gorm, isso foi decidido la atrás.

2021-11-22 12:56 UTC, Melissa-gomes commented on internal/repository/phrase.go
> +	query := fmt.Sprintf("DELETE FROM phrases WHERE file_id = $1 AND key NOT IN (%s)", list)
Não vamos usar Gorm, isso foi decidido la atrás.

2021-11-22 12:57 UTC, Melissa-gomes commented on internal/repository/phrase.go
> +		"SELECT key FROM phrases WHERE file_id = $1",
Não vamos usar Gorm, isso foi decidido la atrás.

2021-11-22 12:57 UTC, Melissa-gomes commented on internal/repository/phrase.go
> +		"INSERT into phrases (id, file_id, key, content) values ($1, $2, $3, $4)",
Não vamos usar Gorm, isso foi decidido la atrás.

2021-11-22 13:54 UTC, SPascareli requested changes
Tem alguns pontos importantes pra discussão aqui nessa PR, olhem pra esses que eu comentei primeiro, mas depois sugiro pensar um pouco mais na operação como um todo, talvez podemos encontrar alguns pontos de melhoria.

2021-11-22 13:54 UTC, SPascareli commented on internal/subscriber/message.go
> +	return rc, nil
Tem bug aqui, conseguem ver o que é?

2021-11-22 13:54 UTC, SPascareli commented on internal/subscriber/handleJSON.go
> +	err = json.Unmarshal(d, &m)
O que vai acontecer se o json não for válido?

2021-11-22 13:54 UTC, SPascareli commented on internal/subscriber/handleJSON.go
> +	m := map[string]interface{}{}
Qual o formato do json que vcs vão receber? Acho que não é tão genérico a ponto de precisar um `map[string]interface{}`.

2021-11-22 13:54 UTC, SPascareli commented on internal/subscriber/handleJSON.go
> +		}
Vc pode pegar a chave e o valor pelo `for range` sem ter que acessar direto assim: `m[index].(string)`.

Alias, esse `.(string)` pode ser evitado se vcs forem menos genéricos no tipo de destino do Unmarshal.

2021-11-22 13:54 UTC, SPascareli commented on internal/subscriber/handleJSON.go
> +		phrasesInFile = append(phrasesInFile, fmt.Sprintf("'%s'", phrase.Key))
Por que precisa desse `Sprintf`?

2021-11-22 13:54 UTC, SPascareli commented on internal/core/services/phrase.go
> +}
Isso aqui é executado para cada phrase, certo? @brendalima  Eu gostaria que me explicasse o passo a passo do que é feito pra cada phrase no arquivo.

2021-11-22 14:04 UTC, brendalima commented on internal/subscriber/handleJSON.go
> +		phrasesInFile = append(phrasesInFile, fmt.Sprintf("'%s'", phrase.Key))
É pra formatar cada key no formato que a query do postgres aceita, pra facilitar a montagem da string da query de `delete` depois. Aqui a gente já coloca as aspas em todas as entradas.

2021-11-22 14:06 UTC, brendalima commented on internal/subscriber/handleJSON.go
> +	m := map[string]interface{}{}
O formato é:
```json
{
  "project.users.invite": "Convidar novo usuário"
}
```

2021-11-22 14:07 UTC, brendalima commented on internal/subscriber/handleJSON.go
> +		phrasesInFile = append(phrasesInFile, fmt.Sprintf("'%s'", phrase.Key))
É pra formatar cada key no formato que a query do postgres aceita, pra facilitar a montagem da string da query de `delete` depois. Aqui a gente já coloca as aspas em todas as entradas

2021-11-22 14:13 UTC, Melissa-gomes commented on internal/subscriber/handleJSON.go
> +		}
mudei para usar o value do for range, mas só podemos fazer a alteração do .(string) depois de mudarmos o Unmarshal

2021-11-22 14:18 UTC, SPascareli commented on internal/subscriber/handleJSON.go
> +	m := map[string]interface{}{}
Não parece ser genérico então, talvez vc pode fazer o Unmarshal pra um tipo mais específico que reflete seu json, o que acha?

2021-11-22 22:44 UTC, pdropaiva commented on internal/subscriber/message.go
> +	return rc, nil
Esse bug, é uma pegadinha da sintaxe do Go talvez.

2021-11-24 13:03 UTC, Melissa-gomes commented on internal/subscriber/handleJSON.go
> +	m := map[string]interface{}{}
pronto, alterado para map[string]string

2021-11-24 13:04 UTC, Melissa-gomes commented on internal/subscriber/handleJSON.go
> +	err = json.Unmarshal(d, &m)
Caso o json for invalido, devolveremos um erro para o usuário.

2021-11-24 13:16 UTC, gabrielmirandaBR commented on internal/subscriber/handleJSON.go
> +		phrasesInFile = append(phrasesInFile, fmt.Sprintf("'%s'", phrase.Key))
Realmente não faz sentido pq a ideia é não criarmos acoplamentos no código. Alteramos a formatação para ser feita no pacote de repository

2021-11-24 13:40 UTC, brendalima commented on internal/core/services/phrase.go
> +}
Para cada `phrase`, nós usamos o `HandlePhrase` para primeiro verificar se a key daquela frase já existe no banco para aquele arquivo, através do `updatePhrase`. O `updatePhrase` procura a key no banco pelo `GetPhrase` e se ele encontrar, verifica se o conteúdo do arquivo é diferente do conteúdo do banco. Se for, ele atualiza no banco.
Caso o `updatePhrase` não encontre a key, seguimos para o `CreatePhrase` que cria todas as novas entradas no banco.
Ao fim, rodamos o `CleanDB` para verificar se alguma key existente no banco para aquele arquivo não existe mais no arquivo. Assim podemos excluir todas as frases que não estão mais no arquivo.

2021-11-24 14:03 UTC, SPascareli commented on internal/core/services/phrase.go
> +}
Então são no mínimo duas queries por frase no arquivo, correto? Uma grande vantagem de estar usando um banco SQL é que ele te da vários comandos que podem ajudar nessa situação, em partircular existe um conceito de `INSERT UPDATE`, que funciona como insert E update na mesma query (o nome não é exatamente esse no postgres, mas o conceito é o mesmo).

Então @brendalima @gabrielmirandaBR @Melissa-gomes, eu queria que vcs desse uma olhada em como funciona esse conceito, como fazer isso em postgres, e depois dizer aqui como vcs aplicariam isso pra melhorar a solução desse problema da importação de frases. Não precisa implementar aqui na PR de fato, acho que o importante é só entender como vcs usariam.

Dica: Da pra reduzir de duas para uma query por frase, em todas as circunstâncias, usando esse conceito.

2021-11-26 17:23 UTC, brendalima commented on internal/core/services/phrase.go
> +}
@SPascareli Nós decidimos subir uma solução nova com base nesse seu comentário, não sei se é exatamente o que você tinha em mente mas achamos que simplificou.
A ideia foi definir uma constraint pra podermos ter vários `file_id` iguais e várias `key` iguais, mas não mais de uma `key` pra um mesmo `file_id`. Assim, conseguimos usar essa solução:
```sql
INSERT into phrases (id, file_id, key, content)
VALUES ($1, $2, $3, $4)
ON CONFLICT (key, file_id)
DO UPDATE SET content = $4
```

Com ela, substituímos as queries de select, de update e de insert por apenas uma query que insere os valores no banco mas, ao identificar que é o mesmo `file_id` com uma mesma `key`, executa um update no conteúdo da frase.
Nessa solução, deixamos de fora a verificação de confirmar que o conteúdo é diferente antes de atualizar pois não sabemos se vale em ganho de performance. Aqui estamos fazendo um update para todas as frases repetidas que recebermos, independente de o conteúdo ter mudado ou não. Valeria ainda ter que buscar uma verificação dessas antes de fazer o update ou seria um trabalho a mais?

2021-11-30 23:27 UTC, pdropaiva requested changes

2021-11-30 23:27 UTC, pdropaiva commented on internal/repository/contracts.go
> +	FindProject(ctx context.Context, projectId string) (string, error)
Igual eu comentei anteriormente, esse `FindProject` está meio perdido aqui, acho que conseguimos seguir sem precisar dele.

2021-11-30 23:27 UTC, pdropaiva commented on internal/subscriber/handleJSON.go
> +		h.sPhrase.HandlePhrase(ctx, phrase)
Acho que esse handlePhrase aqui está muito genérico, eu olho pra ele e não sei o que acontece, e no final é apenas um upsert (createOrUpdate), correto?

2021-11-30 23:27 UTC, pdropaiva commented on internal/subscriber/message.go
> +	s.handler.Process(ctx, rc, file.ID)
Eu vejo um bug aqui, tentem rodar isso local e derruba o banco de dados, acredito que o pubsub vai dar ack em todas as mensagens mesmo não conseguindo salvar no banco.

Acredito isso seria interessante tratar, porque pode ocorrer do banco de dados ficar indisponível por um curto período de tempo.

Fazer o unack em uma mensagem com um json sempre inválido, realmente não faz sentido, porque sempre dará erro, porém banco de dados seria interessante tentar novamente, o que vocês acham?

Ah e passar o `m` para dentro do Process não é uma boa opção.

2021-12-01 15:22 UTC, SPascareli commented on cmd/pubsub/pubsub.go
> +	message := subscriber.MustNewSubscriber(*fService, storage, *handler)
O handler hoje faz mais do que só processar o arquivo de input, ele também chama o service pra fazer a persistência, e esse passo é o mesmo independente do formato do arquivo de input. Então se vc quiser ser bem abstrato teria que ter uma interface tipo "Parser", que tem a implementação `JSONParser` e `CSVParser` por exemplo, mas eu acho que esse subscriber já ta bem abstrato do jeito que ta hoje, não acho que vai ficar melhor adicionando mais essa abstração.

Então caso tenha um input que seja csv eu diria que não tem problema só ter um `switch case` no handler que lida com os tipos de input diferentes.

2021-12-02 14:11 UTC, pdropaiva commented on cmd/pubsub/pubsub.go
> +	message := subscriber.MustNewSubscriber(*fService, storage, *handler)
@SPascareli concordo, vai simplificar mesmo.

2021-12-02 18:47 UTC, Melissa-gomes commented on internal/core/services/file.go
> +}
Esse cenário não existe atualmente, ao criar um projeto, ele já vem associado a um file, caso futuramente tenhamos um endpoint para deletar as files de um projeto e o usuário decidir deletar todas as files desse projeto, ai sim retornaria um array vazio. Faz sentido essa logica?

2021-12-02 19:00 UTC, Melissa-gomes commented on internal/subscriber/message.go
> +	s.handler.Process(ctx, rc, file.ID)
Primeiro ponto, nçao entendemos essa parte:
`Ah e passar o m para dentro do Process não é uma boa opção.`
Pois o `m` não é passado para o `Process`

Segundo ponto:
Realizando alguns testes tentando reproduzir o cenário citado acima, observamos que o PubSub não da Ack nas mensagens e continua tentando processa-las até ter sucesso, o que nos leva a entender que quando o banco for disponibilizado novamente o PubSub processaria a mensagem encontrada e ai sim daria o Ack.

2021-12-02 19:51 UTC, gabrielmirandaBR commented on cmd/pubsub/pubsub.go
> +	message := subscriber.MustNewSubscriber(*fService, storage, *handler)
Seguindo essa linha, poderíamos colocar o `switch case` no método `HandleMessage` e utilizar o `filename[1]` que tem a extensão do arquivo que foi feito o upload para ser os casos do nosso switch, sendo que cada caso chamaria um `handler` que irá processar os arquivos. Seria isso?

2021-12-02 20:20 UTC, pdropaiva commented on internal/core/services/file.go
> +}
> Na nossa logica faz mais sentido retornar um erro caso o projectId não exista pois isso indica ao usuário que o projeto que ele busca está incorreto.

Pensando um pouco sobre essa afirmação, ela é uma regra de negócio atual, logo se eu busco files de um projeto e me retorna vazio, já podemos concluir que o projeto é inválido. O que estou tentando mostrar é que essas duas querys são redundantes.

Sempre que eu pesquisar o files de um projectId, irá me retornar um file pelo menos, a não ser que ele não exista, nesse caso irá retornar vazio.

Repare nas duas querys:
`SELECT id, project_id, status FROM files WHERE project_id = $1`
`SELECT project_id FROM files WHERE project_id = $1`

A primeira é a do GetFiles, a segunda do FindProject. E a mesma query, com o mesmo filtro (where), o que muda e só o dado que traz, uma traz mais coisas, e a do GetFiles já possui todas as informações, não preciso fazer isso duas vezes.

E pra mim não faz sentido uma rota de listagem de files, retornar que o project não existe, essa regra é fraca e pode mudar a qualquer momento, como você mesmo disse, se criar uma rota de deletar project essa regra já para de valer se não houver uma deleção em cascata dos relacionamentos. Quem deveria ser responsável pelo project seria a rota de project, que pelo que entendi não faz parte ainda do nosso escopo.

2021-12-02 20:42 UTC, SPascareli commented on cmd/pubsub/pubsub.go
> +	message := subscriber.MustNewSubscriber(*fService, storage, *handler)
@gabrielmirandaBR acho que não, seria mais um `switch case` no  `Process` pra mim, já que ele que controla o fluxo de importação. Claro que não faria mais muito sentido o arquivo se chamar `handleJSON.go` depois disso, mas acho que não precisa se procupar com isso até esse caso realmente existir de ter mais de um tipo de input.

2021-12-02 22:16 UTC, SPascareli approved these changes
Meu CR e QA está ok! Só olhem com mais carinho para os logs, é bem dificil saber no subscriber se sua mensagem deu certo ou não, sugiro tentar deixar os logs mais explicativos, talvez com os ids do file que ta sendo processado ou algo assim, hoje ta mostarndo só isso:
```
2021/12/02 19:13:15 new message received
2021/12/02 19:13:15 file uploaded
```

Fora isso, pelo meu teste breve funcionou tudo, parabéns pessoal!

2021-12-03 14:14 UTC, gabrielmirandaBR commented on internal/core/services/file.go
> +}
Boa, @pdropaiva! Entendemos o ponto e removemos do código o método `FindProject`. Acrescentamos no `rest` uma mensagem pro usuário caso não encontre nenhum `file`.

2021-12-03 14:14 UTC, gabrielmirandaBR commented on internal/repository/contracts.go
> +	FindProject(ctx context.Context, projectId string) (string, error)
Alterado!

2021-12-03 14:15 UTC, gabrielmirandaBR commented on cmd/pubsub/pubsub.go
> +	message := subscriber.MustNewSubscriber(*fService, storage, *handler)
Beleza!

2021-12-03 14:36 UTC, gabrielmirandaBR commented on internal/subscriber/message.go
> +	s.handler.Process(ctx, rc, file.ID)
@pdropaiva, realmente não estávamos tratando os erros vindos do `Process` e do `HandlePhrase`. Realizamos as alterações.

2021-12-03 22:52 UTC, pdropaiva approved these changes
Pessoal, fiz uma sugestão de alteração simples, que acho que vale vocês olharem, porém já estou aprovando a PR.

Parabéns!

2021-12-03 22:52 UTC, pdropaiva commented on internal/subscriber/handleJSON.go
> +		return errors.New("fail in unmarshal or json format")
Nesse caso aqui, eu logaria o erro, mas retornaria `nil`, o que vocês acham?

Falo isso porque passar esse erro pra frente implicaria em dar `Nack` na mensagem, e ela voltaria para ser reprocessada, porém esse tipo de erro irá se repetir sempre.

Logando a mensagem de erro aqui, e retornando `nil`, o erro é informado porém a mensagem não tentará ser reprocessada novamente (pois ela estará sempre errada).

2021-12-06 21:12 UTC, merged