[TRAD-18] Na rota de listar files, adicionar o filtro obrigatório de project id
ditointernet/tradulab-service pull request #13
Opened 2021-11-18 14:15 UTC by brendalima

Acrescenta a rota `/files/:projectId` que permite recuperar todos os arquivos pertencentes a um determinado projeto.

2021-11-18 14:45 UTC, SPascareli commented on internal/rest/file.go
> +	projectId := ctx.Param("projectId")
O que acontece se não for mandado?

2021-11-18 14:48 UTC, Melissa-gomes commented on internal/rest/file.go
> +	projectId := ctx.Param("projectId")
a rota só existe com o project Id, logo se você não mandar o project Id vai dar not found (404), isso é a nossa garantia da obrigatoriedade do projectId

2021-11-18 14:56 UTC, SPascareli commented on internal/rest/file.go
> +	projectId := ctx.Param("projectId")
Bom demais!

2021-11-18 15:00 UTC, Melissa-gomes commented on cmd/api/main.go
> +	router.GET("/files/:projectId", rFile.GetAllFiles)
as outras rotas lidam apenas com um aquivo por vez, enquanto essa nos devolve mais de um arquivo por isso da semântica no plural

2021-11-18 15:14 UTC, SPascareli commented on cmd/api/main.go
> +	router.GET("/files/:projectId", rFile.GetAllFiles)
Enquanto eu não ligo muito pra semântica de rotas, imagina o client que vai usar essa api, ele vai ter um baseurl pra rota de file tipo `https://tradulab.com/file` que ele usa em todas as rotas...menos nessa rota específica, que ele vai ter que concatenar um `s` na rota.

Então minha sugestão é decidir em um ou outro, ou `file` ou `files`, e manter consistente. Se decidirem por `file`, não precisa mudar nessa PR, pra não poluir, pode ser outra.

De qualquer forma, não vou bloquear a PR por isso.

2021-11-18 15:15 UTC, SPascareli approved these changes
boa!

2021-11-19 21:18 UTC, nborgesfilho requested changes

2021-11-19 21:18 UTC, nborgesfilho commented on cmd/api/main.go
> +	router.GET("/files/:projectId", rFile.GetAllFiles)
Pode ser motivo pra bloqueio sim, visto que se subirmos pra produção e alguém começar a utilizar isso, caso isso mude depois será preciso alterar quem consome o serviço. Acho interessante sempre utilizar um padrão, ou tudo no singular ou tudo no plural.

2021-11-24 13:10 UTC, uriell approved these changes

2021-11-24 13:33 UTC, gabrielmirandaBR commented on cmd/api/main.go
> +	router.GET("/files/:projectId", rFile.GetAllFiles)
Resolvemos padronizar o endpoint no singular para `file`.

2021-11-24 13:33 UTC, merged