[TRAD-20] Criar uma rota de buscar uma phrase por phrase id
ditointernet/tradulab-service pull request #16
Opened 2021-12-07 17:43 UTC by Melissa-gomes

router for get phrase by id

2021-12-10 18:41 UTC, SPascareli commented on internal/core/services/phrase.go
> +
espaço

2021-12-10 18:42 UTC, SPascareli commented on internal/repository/phrase.go
> +
espaço

2021-12-10 18:59 UTC, SPascareli approved these changes
CR ok, falta o QA.

2021-12-10 19:20 UTC, SPascareli commented
Acho que é um pouco estranho vc retornar `500`  quando o erro é que uma phrase não foi encontrada, tem alguma ideia de como podemos fazer ele retornar um `404`  que é mais adequado?

Deixei como comentário pra ser mais um brainstorming, do que necessariamente um request de mudança.

2021-12-10 19:20 UTC, SPascareli approved these changes
QA ok!

2021-12-13 12:52 UTC, uriell approved these changes

2021-12-16 23:06 UTC, SPascareli requested changes

2021-12-16 23:06 UTC, SPascareli commented on internal/rest/phrase.go
> +		if err.Error() == "phrase not found" {
Usar a string do erro para verificar se é 404 não é uma boa, a string do erro é algo feito para nós (os devs) olharmos, não para o código tormar decisões com base nisso.

Consegue pensar em alguma outra forma?

2021-12-23 13:21 UTC, gabrielmirandaBR commented
@SPascareli optamos por realizar o tratamento de erro do método `GetPhrasesById` utilizando a forma mais genérica com um construtor para cada tipo de erro. As alterações já foram realizadas.

2021-12-23 13:26 UTC, SPascareli approved these changes
:+1:

2021-12-23 21:28 UTC, merged