[TRAD-19] Criar uma rota de listar phrases com paginação, com o filtro de file id
ditointernet/tradulab-service pull request #17
Opened 2021-12-08 17:08 UTC by Melissa-gomes

Como testar:

Com o seu banco já populado faça uma requisição na rota:

`http://localhost:8080/phrases?fileId=:id&page=:numeroDaPagina`

o resultado esperado deve ser um array com a quantidade máxima de 100 resultados dependendo da pagina que voce estiver.

Aviso: isso varia com a quantidade de phrases populadas no seu banco

2021-12-10 18:37 UTC, SPascareli requested changes

2021-12-10 18:37 UTC, SPascareli commented on internal/repository/phrase.go
> +	numberPage, _ := strconv.Atoi(page)
Meio estranho receber o `page` como string e parsear pra int dentro do repo, não acha? Acho que tem lugares melhores pra fazer esse tipo de transformação.

Alias, pensa no que iria acontecer aqui caso `page` não seja um número váildo, por exemplo.

2021-12-10 18:37 UTC, SPascareli commented on internal/repository/phrase.go
> +	offset := limit * (numberPage - 1)
Esse tipo de lógica é um pouco arriscada, principalmente se vc não está validando se `numberPage` é um número > 0;

2021-12-10 18:37 UTC, SPascareli commented on internal/repository/phrase.go
> +		err = allPhrases.Scan(&phrase.ID, &phrase.FileID, &phrase.Key, &phrase.Content)
Ta um pouco obscuro pra mim aqui como que a ordem desses campos no `Scan` é definida, tenho certeza que tem alguma lógica nisso, mas se vc passar os campos explicitamente no `SELECT` isso fica mais obvio olhando pelo código, o que acha?

2021-12-10 18:37 UTC, SPascareli commented on driven/dto.go
> +}
Onde isso é usado?

2021-12-10 18:37 UTC, SPascareli commented on internal/rest/phrase.go
> +	} else {
Se vc tem um return dentro do `if`, então não precisa ter um `else`.

2021-12-10 20:08 UTC, gabrielmirandaBR commented on internal/repository/phrase.go
> +	offset := limit * (numberPage - 1)
@SPascareli, validamos o `numberPage` para ser um número inteiro positivo. Isso remove o risco dessa lógica?

2021-12-13 12:54 UTC, uriell approved these changes

2021-12-13 18:39 UTC, SPascareli requested changes

2021-12-13 18:39 UTC, SPascareli commented on internal/core/services/phrase.go
> +	numberPage, err := strconv.Atoi(page)
Ainda acho que tem lugar melhor pra fazer essa transformação, mesmo para o service não faz sentido receber um `page` como string.

2021-12-13 18:39 UTC, SPascareli commented on internal/repository/phrase.go
> +	allPhrases, err := p.cli.QueryContext(ctx, "SELECT id, file_id, key, content FROM phrases WHERE file_id = $3 OFFSET $1 LIMIT $2", offset, limit, fileId)
Que tal ordenar os parametros `$1 $2 $3` de forma sequencial pra ficar mais fácil de ler?

2021-12-13 18:45 UTC, SPascareli commented on internal/repository/phrase.go
> +	offset := limit * (numberPage - 1)
Não completamente, o repo ainda recebe um `int` que pode ser negativo, até onde ele sabe, a validação no service só garante que **aquele** service não chama ele com `page <= 0`, mas não impede que qualquer outra parte do código faça isso.

Idealmente vc faria seu código de tal forma que essa situação se torna impossível de acontecer, tipo um `unsigned int` que nunca pode ser negativo, mas ainda pode ser zero então não resolve nesse caso, então talvez seja melhor validar 2 vezes: uma vez no código que lida com o input diretamente (o controller) e uma segunda vez no repo, antes de usar o page.

2021-12-16 23:00 UTC, SPascareli requested changes
Se não passar um número de página na request ele quebra pq ele assume `0`, talvez um comportamento melhor seja assumir 1 por padrão caso não mande na request, o que acha?

2021-12-16 23:03 UTC, SPascareli commented on internal/repository/phrase.go
> +	limit := 100
O que acha de receber o limite padrão via env? Pelo menos não teria que recompilar o código caso queira mudar.

2021-12-16 23:21 UTC, SPascareli commented
@brendalima @Melissa-gomes @gabrielmirandaBR @uriell @pdropaiva qual o pensamento de vcs sobre o comportamento que tem hoje de retornar 404 caso vc passe uma página que não tem dados na paginação?

Eu tava pensando que é um pouco estranho, pq não necessariamente é um erro pedir a página 2 se só tem 1 página de dados, não é que não existem dados pra mostrar daquele `fileId`, vc só ta vendo além do que existe hoje. Agora o que seria um 404 é se o `fileId` não existe, ai realmente vc ta solicitando uma entidade que não existe no banco então 404 é válido.

Então nesse pensamento solicitar uma página que não tem dados não é um erro, só não retorna nada, mas queria a opinião de vcs, devem ter motivos que tornariam isso ruim.

2021-12-17 17:01 UTC, gabrielmirandaBR commented
> Se não passar um número de página na request ele quebra pq ele assume `0`, talvez um comportamento melhor seja assumir 1 por padrão caso não mande na request, o que acha?

@SPascareli, implementamos essa validação!

2021-12-17 19:54 UTC, gabrielmirandaBR commented
> @brendalima @Melissa-gomes @gabrielmirandaBR @uriell @pdropaiva qual o pensamento de vcs sobre o comportamento que tem hoje de retornar 404 caso vc passe uma página que não tem dados na paginação?
> 
> Eu tava pensando que é um pouco estranho, pq não necessariamente é um erro pedir a página 2 se só tem 1 página de dados, não é que não existem dados pra mostrar daquele `fileId`, vc só ta vendo além do que existe hoje. Agora o que seria um 404 é se o `fileId` não existe, ai realmente vc ta solicitando uma entidade que não existe no banco então 404 é válido.
> 
> Então nesse pensamento solicitar uma página que não tem dados não é um erro, só não retorna nada, mas queria a opinião de vcs, devem ter motivos que tornariam isso ruim.

@SPascareli, durante a planning discutimos sobre essa questão. O que acha dessa lógica? 
Ao acessar a rota de buscar frases pelo id do arquivo, enviaremos via `header` o total de frases (count) e com o `limitPage` podemos criar a lógica de saber qual a quantidade máxima de páginas e personalizar o status HTTP.
Como o  `limitPage` está, agora, sendo setado no arquivo .env teremos que passar essa variável, primeiramente, via intenção de dependêcia para o `repo` e ir seguindo o fluxo até chegar na camada de `rest`.  O que acha?

2021-12-20 14:18 UTC, SPascareli commented on internal/core/services/file.go
> +		return domain.File{}, errors.New("error trying to create the file, status changed to failed")
Mas, pq precisaria disso? E talvez fosse melhor estar em outra PR mesmo, não tem muito a ver com essa aqui e só vai fazer demorar mais  o QA.

2021-12-20 17:34 UTC, gabrielmirandaBR commented on internal/core/services/file.go
> +		return domain.File{}, errors.New("error trying to create the file, status changed to failed")
Beleza, retirei essa parte da PR. @uriell achava que ter o status `CREATED` e `SUCCESS` não resumia bem todas as situações que poderiam acontecer com o arquivo.

2021-12-20 17:56 UTC, SPascareli commented on internal/core/services/file.go
> +		return domain.File{}, errors.New("error trying to create the file, status changed to failed")
Faz sentido, mas criar o arquivo na API como `failed` não faz muito, faria mais sentido ser `failed` se falhar no processamento do subscriber, por exemplo, mas a gente discute isso em outra PR.

2021-12-20 17:57 UTC, SPascareli approved these changes
QA OK! :clap:

2021-12-21 13:09 UTC, merged