Tradulab 82
ditointernet/tradulab-service pull request #2
Opened 2021-09-17 13:46 UTC by brendalima

Initial structure and initial controller and service for files.

2021-09-17 14:18 UTC, sergio-silva commented on internal/core/domain/domain.go
> +type Direction int
@brendalima fiquei curioso com esse tipo Direction aqui... qual foi a ideia aqui nesse caso?

2021-09-17 14:20 UTC, sergio-silva commented on internal/core/services/file.go
> +	extenssion := file.P[len(file.P)-4:]
Essa palavra aqui é com um S apenas

2021-09-17 14:22 UTC, sergio-silva commented on internal/core/services/file.go
> +	extenssion := file.P[len(file.P)-4:]
Não conheço muito de Go... mas essa é a melhor forma de pegarmos a extensão de um arquivo mesmo? Pegando os útlimos 4 caracteres do seu pathname? Não existe nenhum método da própria lib de file que nos retorne a extensão de um dado arquivo?

2021-09-17 15:09 UTC, pdropaiva requested changes

2021-09-17 15:09 UTC, pdropaiva commented on internal/core/services/file.go
> +	CheckFile() (drivers.File, error)
Acredito que o `CheckFile` deva receber um `domain.File` como parâmetro e retornar apenas um error, o que acham?

2021-09-17 15:09 UTC, pdropaiva commented on internal/rest/file.go
> +func (f File) CreateFile(ctx *gin.Context) {
O que vocês acham de receber no body da requisição o `projectId` e o `filePath`? Utilizando o Bind do Gin para já adicionar os valores à uma struct. (usaremos a dto.File ou domain.File?)
- Se fizermos o bind da API para `dto.File` será necessário transformar ela para `domain.File` para utilizar nos services de domínio.

2021-09-17 16:50 UTC, brendalima commented on internal/core/services/file.go
> +	extenssion := file.P[len(file.P)-4:]
Acho que como no momento só estamos aceitando `.csv`, não nos preocupamos muito com isso porque mesmo que as extensões possam ter mais ou menos dígitos, não vai passar na checagem de qualquer forma.
Mas encontramos esse método `Ext` do filepath que parece checar isso certinho:
https://pkg.go.dev/path/filepath#Ext

2021-09-20 14:05 UTC, pdropaiva requested changes

2021-09-20 14:05 UTC, pdropaiva commented on internal/core/services/file.go
> +	CheckFile(*drivers.File) error
Pensando melhor sobre a assinatura desse método, ele está no nosso domínio já, acho que faz mais sentido ele trabalhar com o `*domain.File` ao invés do `*drivers.File` o que vocês acham?

2021-09-20 14:05 UTC, pdropaiva commented on internal/rest/file.go
> +	}
Sobre o comentário anterior, se forem implementá-lo, esse código teria que ser feito antes da chamada do `CheckFile`, para ele ser usado lá.

2021-09-22 18:43 UTC, brendalima commented on internal/core/domain/domain.go
> +type Direction int
Ele tá aí pra controle da direção de um novo voto recebido pra uma sugestão de tradução. A sugestão pode receber um voto negativo e aí ele é -1 ou o positivo 1.

2021-09-22 18:43 UTC, brendalima commented on Dockerfile
> +COPY . .
Acho que não entendi, Nei. Esses comandos estão no Dockerfile.

2021-09-23 13:22 UTC, merged