Tradulab 3
ditointernet/tradulab-service pull request #4
Opened 2021-09-27 18:28 UTC by Melissa-gomes

- [x] Conexão com Postgres via Docker

- [x] Criar variáveis de ambiente

- [x] Persistência de dados

2021-09-28 12:58 UTC, uriell approved these changes
Ficou bom, só remover o `.gitkeep` de dentro do `internal/core/ports` já que ele é usado pra "manter uma pasta vazia", e agora já temos pelo menos 1 arquivo nela

2021-09-28 13:35 UTC, brendalima commented
> Ficou bom, só remover o `.gitkeep` de dentro do `internal/core/ports` já que ele é usado pra "manter uma pasta vazia", e agora já temos pelo menos 1 arquivo nela

Valeu Uriell. Ele já está excluído, está aparecendo só como "empty file removed" nesse PR.

2021-09-28 18:24 UTC, pdropaiva requested changes

2021-09-28 18:24 UTC, pdropaiva commented on internal/core/services/file.go
> +	repo repository.Database
O que vocês acham de ao invés de utilizar a struct `Database` direto aqui, utilizamos a interface `Repository` criada?

2021-09-28 18:24 UTC, pdropaiva commented on internal/rest/file.go
> +	}
Aqui vejo dois pontos:

- Por que estamos salvando no banco, antes de validar o arquivo? Digamos que eu envie um arquivo de extensão inválida, essa rota irá retornar pra mim um erro de extensão inválida, mas o arquivo já estará cadastrado no banco.
- O `SaveFile`, só salva no banco, se houver algum erro nele, não acredito que seja um status `BadRequest`, acredito que se der algum erro aqui deve estar mais associado com o processo de salvar no banco (ele pode estar indisponível ou sobrecarregado, por exemplo), nesse caso acho que faz mais sentido um `InternalServerError` o que vocês acham?

2021-09-28 18:24 UTC, pdropaiva commented on internal/rest/file.go
> -		"file":    file,
O que vocês acham de retornar aqui o ID do `File` gerado?

2021-09-28 18:24 UTC, pdropaiva commented on repository/config.go
> +	err := godotenv.Load(".env")
Porque adicionamos essa dependência `godotenv`? Não seria mais interessante o `docker-compose` servir as variáveis de ambiente, ao invés da aplicação fazer o load de um arquivo?

Aqui têm mais detalhes de como funciona: https://docs.docker.com/compose/env-file/

2021-09-28 19:49 UTC, SPascareli requested changes

2021-09-28 19:49 UTC, SPascareli commented on repository/postgres.go
> +package repository
Não olhei a fundo, mas vou deixar o comentário que já havia feito antes: Um pacote chamado `repository` que vai lidar com a lógica de salvar todos os tipos de entidades não é muito bom, eu sugiro dividir os repos de forma contextual, tipo um repo pra `files`, um pra `phrases` etc.

Dessa forma, a conexão com o banco não ficaria a cargo dos repos (já que vc teria que conectar multiplas vezes em multiplos repos), então eu sugeriria fazer a conexão  e receber o client do banco já conectado ( no caso o objeto do tipo `*gorm.DB`) via injeção nos repos.

2021-09-28 19:49 UTC, SPascareli commented on repository/config.go
> +	}
A ideia de pegar as envs separadamente da instanciação do repo é boa, mas a melhor prática aqui seria essa parte estar na `main`, assim apenas a `main` lidaria com envs de qualquer forma.

2021-09-28 20:11 UTC, brendalima commented on repository/config.go
> +	}
Nós temos duas `main`, a da `api` e a das `migrations`. Como teríamos que usar o mesmo código nas duas, achamos que seria mais fácil de reutilizar o mesmo código assim.

2021-09-29 20:14 UTC, pdropaiva requested changes

2021-09-29 20:14 UTC, pdropaiva commented on internal/repository/file.go
> +	cli *adapters.Database
O que vocês acham de trabalhar aqui com o `*sql.DB` é um padrão do Go para implementação de database SQL like https://pkg.go.dev/database/sql@go1.16#DB

O gorm já retorna essa implementação chamando o método `DB()`: https://gorm.io/docs/generic_interface.html#content-inner

2021-09-29 21:14 UTC, pdropaiva requested changes

2021-09-29 21:14 UTC, pdropaiva commented on internal/rest/file.go
> +		"file_id": file.ID,
O que vocês acham de retornar um `id` ao invés de `file_id`? Essa é uma rota de criar file, por isso já deixa implícito que o `id` é de um `file`, a ideia do REST é exatamente deixar a API bem atrelada às entidades.

Segue um post no medium falando um pouco mais sobre API RESTful: https://medium.com/@mwaysolutions/10-best-practices-for-better-restful-api-cbe81b06f291
A primeira boa prática do link acho que ficou bagunçado não está dando pra entender direito, pode "pular" ela.

2021-09-29 21:21 UTC, pdropaiva approved these changes

2021-09-30 17:57 UTC, SPascareli commented on adapters/postgres.go
> +}
O que acham de fazer mais ou menos assim?

```suggestion
func NewDatabase(in *Config) *gorm.DB {
	dsn := fmt.Sprintf(
		"host=%s user=%s password=%s dbname=%s port=%s sslmode=disable",
		in.Host,
		in.User,
		in.Password,
		in.DbName,
		in.Port,
	)

	database, err := gorm.Open(postgres.Open(dsn), &gorm.Config{})
	if err != nil {
		fmt.Println("Could not connect to the Postgres Database")
		log.Fatal("error: ", err)
	}

	return database
}
```

* O principal aqui é que antes tinha uma dependência implicita de ordem, por exemplo, se vc chamasse o `AutoMigrate` antes do `StartPostgres`...ia estourar! Agora isso é simplesmente impossível de acontecer.
* `NewDatabase` te retona o db do gorm, que é o que vcs precisam pra passar para os repos, isso tira a necessidade de ter o `GetDatabse`;
* O `AutoMigrate`, honestamente, eu acho mais interessante só chamar na main do `migrate` direto;

No geral eu acho esse pacote `adapters` desnecessário, mas se forem manter ele, eu diria que essa forma fica um pouco melhor.

O que acham?

2021-09-30 17:59 UTC, SPascareli commented on internal/repository/file.go
> +}
Acho que é bem assim mesmo!

Só não entendi bem pq vcs tão usando o gorm, mas só passam o sql padrão do go pros repos, não é meio inútil então esse form?

2021-09-30 18:22 UTC, brendalima commented on internal/repository/file.go
> +}
Então Sérgio, a ideia no fim acabou sendo que a gente usasse o gorm só pras conexões e automigrations, mas mantivesse o código com o sql padrão porque o gorm e outras bibliotecas tem acesso a ele. Então essa foi uma sugestão do Paiva, pra evitar que tivéssemos o trabalho de fazer uma interface que funcionasse com qualquer lib que não fosse o gorm, fazemos um código que funciona só com o sql padrão pras queries mesmo, já que tínhamos concordado também que escrever as queries seria mais interessante pro nosso aprendizado do que usar os métodos prontos do gorm. Mas ainda estamos usando o gorm pra outras coisas.

2021-09-30 18:26 UTC, gabrielmirandaBR commented on adapters/postgres.go
> +}
Bom demais, dessa maneira enxugou muito o código! :nerd_face:

2021-09-30 20:46 UTC, SPascareli commented on docker-compose.yml
> +
Tentando rodar aqui eu tive problemas por causa desses networks, não acho que vcs precisam disso, deve funcionar normal sem.

2021-09-30 20:47 UTC, SPascareli requested changes
Geralmente nós adicionamos um `.env.sample` com um exemplo das envs necessárias pra rodar os projetos, sugiro adicionar.

2021-09-30 20:55 UTC, Melissa-gomes commented on docker-compose.yml
> +
Já retiramos o network e continua funcionando normalmente e também já adicionamos o .env.sample

2021-09-30 21:00 UTC, SPascareli approved these changes
Parabéns :clap: Na próxima ajustamos mais algumas outras coisas, mas o setup ta bem legal.

2021-09-30 21:01 UTC, merged