[Trad 13] Criar tópico no PubSub
ditointernet/tradulab-service pull request #9
Opened 2021-10-25 17:36 UTC by Melissa-gomes

2021-10-29 18:44 UTC, nborgesfilho requested changes

2021-10-29 18:44 UTC, nborgesfilho commented on .env-sample
> +PROJECT_ID=dito-tradulab
talvez versionar utilizando um bucket e project de staging

2021-10-29 18:44 UTC, nborgesfilho commented on cmd/pubsub/pubsub.go
> +	fmt.Println("Listening to subscription")
O que acha de utilizar algum logger aqui?

2021-10-29 18:44 UTC, nborgesfilho commented on cmd/pubsub/pubsub.go
> +	sub := client.Subscription("files-topic-sub")
Favor adicionar como variável de ambiente.

2021-10-29 18:44 UTC, nborgesfilho commented on cmd/pubsub/pubsub.go
> +		fmt.Printf("%s", string(m.Data))
not sure if we should print every message received.
maybe using a logger with the debug options.

2021-10-29 18:44 UTC, nborgesfilho commented on cmd/pubsub/pubsub.go
> +		fmt.Printf("%s", string(m.Data))
what do u think @pdropaiva @SPascareli

2021-11-12 17:01 UTC, uriell requested changes
só tinha um comentário mesmo

2021-11-12 17:01 UTC, uriell commented on adapters/config.go
> +		Subscription:   os.Getenv("SUBSCRIPTION"),
acho q o nome desse env poderia ser mais específico, tipo FILE_UPLOAD_SUBSCRIPTION

2021-11-16 18:39 UTC, uriell approved these changes

2021-11-18 13:02 UTC, merged